#################     服务器配置     #################
server:
  port: 11503
  undertow:
    accesslog:
      enabled: true
      pattern: "%t %a &quot;%r&quot; %s (%D ms)"
      dir: /data/logs/undertow/${spring.application.name}/access-logs/
  servlet:
    context-path: /foundation

#################     spring公共配置     #################
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: foundation
  main:
    # 支持循环依赖注入
    allow-circular-references: true
    # bean名相同覆盖
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 192.168.153.170:8848
      config:
        server-addr: 192.168.153.170:8848
        #        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
      - nacos:common.yml

#################     项目独有配置     #################
swagger:
  enable: true
  package-path: com.cskaoyan.duolai.clean.foundation.controller
  title: 家政服务-基础实施服务接口文档
  description: 用于基础设施服务进行管理
  contact-name: 王道训练营
  version: v1.0


#################     日志配置     #################
logging:
  level:
    org.apache.http: info #es请求日志
feign:
  enable: true
