server:
  port: 11500  #端口
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 192.168.153.170:8848
      config:
        server-addr: 192.168.153.170:8848
        #        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
