#################     服务器配置     #################
server:
  port: 11505
  undertow:
    accesslog:
      enabled: true
      pattern: "%t %a &quot;%r&quot; %s (%D ms)"
      dir: /data/logs/undertow/${spring.application.name}/access-logs/
  servlet:
    context-path: /pay

#################     spring公共配置     #################
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: pay
  main:
    # 支持循环依赖注入
    allow-circular-references: true
    # bean名相同覆盖
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 192.168.163.138:8848
      config:
        server-addr: 192.168.163.138:8848
        #        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:common.yml

jzo2o:
  job:
    trading:
      count: ${job.trading.count} #每次查询交易单的数量
    refund:
      count: ${job.refund.count} #每次查询退款单的数量
  qrcode: #二维码生成参数
    margin: ${qrcode.margin} #边距，二维码和背景之间的边距
    fore-color: ${qrcode.fore-color} #二维码颜色，默认黑色
    back-color: ${qrcode.back-color} #背景色，默认白色
    #低级别的像素块更大，可以远距离识别，但是遮挡就会造成无法识别。高级别则相反，像素块小，允许遮挡一定范围，但是像素块更密集。
    error-correction-level: ${qrcode.error-correction-level} #纠错级别，可选参数：L、M、Q、H，默认：M
    width: ${qrcode.width} #宽
    height: ${qrcode.height} #高

#################     项目独有配置     #################
mysql:
  db-name: pay
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.cskaoyan.duolai.clean.pay.mapper
swagger:
  enable: true
  package-path: com.jzo2o.pay.controller
  title: 家政服务-支付服务接口文档
  description: 该微服务完记录交易、对接支付宝微信支付平台。
  contact-name: 传智教育·研究院
  contact-url: http://www. .cn/
  contact-email: yjy@ .cn
  version: v1.0

#################     日志配置     #################
logging:
  level:
    com.jzo2o: debug
    org.apache.http: info #es请求日志
feign:
  enable: true
