#################     服务器配置     #################
server:
  port: 11509
  undertow:
    accesslog:
      enabled: true
      pattern: "%t %a &quot;%r&quot; %s (%D ms)"
      dir: /data/logs/undertow/${spring.application.name}/access-logs/
  servlet:
    context-path: /housekeeping

#################     spring公共配置     #################
spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: housekeeping
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
      - nacos:common.yml
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 192.168.163.138:8848
      config:
        server-addr: 192.168.163.138:8848
        #        server-addr: 127.0.0.1:8848
        file-extension: yml
  main:
    # 支持循环依赖注入
    allow-circular-references: true
    # bean名相同覆盖
    allow-bean-definition-overriding: true
#################     项目独有配置     #################
mysql:
  db-name: housekeeping
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.cskaoyan.duolai.clean.housekeeping.dao.mapper
#################     日志配置     #################
logging:
  level:
    com.cskaoyan.duolai.clean.foundations.mapper: debug
    org.apache.http: info #es请求日志
feign:
  enable: true
